language: php
php: 
  - 5.3

env:
  - DB=MYSQL CORE_RELEASE=3.0, php: 5.3
  - DB=MYSQL CORE_RELEASE=3.1, php: 5.3

branches:
  only:
    - tests

before_script:
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script: 
 - phpunit silverstripe-zenvalidator/tests